# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HungryNow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!

  # Pods for HungryNow
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'ExytePopupView'
  pod 'SwiftKeychainWrapper'

  target 'HungryNowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HungryNowUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
